//! Key codes for keyboard shortcuts.

use serde::{Deserialize, Serialize};

/// Key codes (subset of common keys)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum KeyCode {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Escape,
    Tab,
    Space,
    Enter,
    Backspace,
    Delete,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    Home,
    End,
    PageUp,
    PageDown,
}

impl KeyCode {
    /// Get display name
    pub fn name(&self) -> &'static str {
        match self {
            KeyCode::A => "A",
            KeyCode::B => "B",
            KeyCode::C => "C",
            KeyCode::D => "D",
            KeyCode::E => "E",
            KeyCode::F => "F",
            KeyCode::G => "G",
            KeyCode::H => "H",
            KeyCode::I => "I",
            KeyCode::J => "J",
            KeyCode::K => "K",
            KeyCode::L => "L",
            KeyCode::M => "M",
            KeyCode::N => "N",
            KeyCode::O => "O",
            KeyCode::P => "P",
            KeyCode::Q => "Q",
            KeyCode::R => "R",
            KeyCode::S => "S",
            KeyCode::T => "T",
            KeyCode::U => "U",
            KeyCode::V => "V",
            KeyCode::W => "W",
            KeyCode::X => "X",
            KeyCode::Y => "Y",
            KeyCode::Z => "Z",
            KeyCode::Num0 => "0",
            KeyCode::Num1 => "1",
            KeyCode::Num2 => "2",
            KeyCode::Num3 => "3",
            KeyCode::Num4 => "4",
            KeyCode::Num5 => "5",
            KeyCode::Num6 => "6",
            KeyCode::Num7 => "7",
            KeyCode::Num8 => "8",
            KeyCode::Num9 => "9",
            KeyCode::F1 => "F1",
            KeyCode::F2 => "F2",
            KeyCode::F3 => "F3",
            KeyCode::F4 => "F4",
            KeyCode::F5 => "F5",
            KeyCode::F6 => "F6",
            KeyCode::F7 => "F7",
            KeyCode::F8 => "F8",
            KeyCode::F9 => "F9",
            KeyCode::F10 => "F10",
            KeyCode::F11 => "F11",
            KeyCode::F12 => "F12",
            KeyCode::Escape => "Esc",
            KeyCode::Tab => "Tab",
            KeyCode::Space => "Space",
            KeyCode::Enter => "Enter",
            KeyCode::Backspace => "Backspace",
            KeyCode::Delete => "Del",
            KeyCode::ArrowUp => "Up",
            KeyCode::ArrowDown => "Down",
            KeyCode::ArrowLeft => "Left",
            KeyCode::ArrowRight => "Right",
            KeyCode::Home => "Home",
            KeyCode::End => "End",
            KeyCode::PageUp => "PgUp",
            KeyCode::PageDown => "PgDn",
        }
    }

    /// Convert from egui Key
    pub fn from_egui(key: egui::Key) -> Option<Self> {
        Some(match key {
            egui::Key::A => KeyCode::A,
            egui::Key::B => KeyCode::B,
            egui::Key::C => KeyCode::C,
            egui::Key::D => KeyCode::D,
            egui::Key::E => KeyCode::E,
            egui::Key::F => KeyCode::F,
            egui::Key::G => KeyCode::G,
            egui::Key::H => KeyCode::H,
            egui::Key::I => KeyCode::I,
            egui::Key::J => KeyCode::J,
            egui::Key::K => KeyCode::K,
            egui::Key::L => KeyCode::L,
            egui::Key::M => KeyCode::M,
            egui::Key::N => KeyCode::N,
            egui::Key::O => KeyCode::O,
            egui::Key::P => KeyCode::P,
            egui::Key::Q => KeyCode::Q,
            egui::Key::R => KeyCode::R,
            egui::Key::S => KeyCode::S,
            egui::Key::T => KeyCode::T,
            egui::Key::U => KeyCode::U,
            egui::Key::V => KeyCode::V,
            egui::Key::W => KeyCode::W,
            egui::Key::X => KeyCode::X,
            egui::Key::Y => KeyCode::Y,
            egui::Key::Z => KeyCode::Z,
            egui::Key::Num0 => KeyCode::Num0,
            egui::Key::Num1 => KeyCode::Num1,
            egui::Key::Num2 => KeyCode::Num2,
            egui::Key::Num3 => KeyCode::Num3,
            egui::Key::Num4 => KeyCode::Num4,
            egui::Key::Num5 => KeyCode::Num5,
            egui::Key::Num6 => KeyCode::Num6,
            egui::Key::Num7 => KeyCode::Num7,
            egui::Key::Num8 => KeyCode::Num8,
            egui::Key::Num9 => KeyCode::Num9,
            egui::Key::F1 => KeyCode::F1,
            egui::Key::F2 => KeyCode::F2,
            egui::Key::F3 => KeyCode::F3,
            egui::Key::F4 => KeyCode::F4,
            egui::Key::F5 => KeyCode::F5,
            egui::Key::F6 => KeyCode::F6,
            egui::Key::F7 => KeyCode::F7,
            egui::Key::F8 => KeyCode::F8,
            egui::Key::F9 => KeyCode::F9,
            egui::Key::F10 => KeyCode::F10,
            egui::Key::F11 => KeyCode::F11,
            egui::Key::F12 => KeyCode::F12,
            egui::Key::Escape => KeyCode::Escape,
            egui::Key::Tab => KeyCode::Tab,
            egui::Key::Space => KeyCode::Space,
            egui::Key::Enter => KeyCode::Enter,
            egui::Key::Backspace => KeyCode::Backspace,
            egui::Key::Delete => KeyCode::Delete,
            egui::Key::ArrowUp => KeyCode::ArrowUp,
            egui::Key::ArrowDown => KeyCode::ArrowDown,
            egui::Key::ArrowLeft => KeyCode::ArrowLeft,
            egui::Key::ArrowRight => KeyCode::ArrowRight,
            egui::Key::Home => KeyCode::Home,
            egui::Key::End => KeyCode::End,
            egui::Key::PageUp => KeyCode::PageUp,
            egui::Key::PageDown => KeyCode::PageDown,
            _ => return None,
        })
    }

    /// Convert to egui Key
    pub fn to_egui(self) -> egui::Key {
        match self {
            KeyCode::A => egui::Key::A,
            KeyCode::B => egui::Key::B,
            KeyCode::C => egui::Key::C,
            KeyCode::D => egui::Key::D,
            KeyCode::E => egui::Key::E,
            KeyCode::F => egui::Key::F,
            KeyCode::G => egui::Key::G,
            KeyCode::H => egui::Key::H,
            KeyCode::I => egui::Key::I,
            KeyCode::J => egui::Key::J,
            KeyCode::K => egui::Key::K,
            KeyCode::L => egui::Key::L,
            KeyCode::M => egui::Key::M,
            KeyCode::N => egui::Key::N,
            KeyCode::O => egui::Key::O,
            KeyCode::P => egui::Key::P,
            KeyCode::Q => egui::Key::Q,
            KeyCode::R => egui::Key::R,
            KeyCode::S => egui::Key::S,
            KeyCode::T => egui::Key::T,
            KeyCode::U => egui::Key::U,
            KeyCode::V => egui::Key::V,
            KeyCode::W => egui::Key::W,
            KeyCode::X => egui::Key::X,
            KeyCode::Y => egui::Key::Y,
            KeyCode::Z => egui::Key::Z,
            KeyCode::Num0 => egui::Key::Num0,
            KeyCode::Num1 => egui::Key::Num1,
            KeyCode::Num2 => egui::Key::Num2,
            KeyCode::Num3 => egui::Key::Num3,
            KeyCode::Num4 => egui::Key::Num4,
            KeyCode::Num5 => egui::Key::Num5,
            KeyCode::Num6 => egui::Key::Num6,
            KeyCode::Num7 => egui::Key::Num7,
            KeyCode::Num8 => egui::Key::Num8,
            KeyCode::Num9 => egui::Key::Num9,
            KeyCode::F1 => egui::Key::F1,
            KeyCode::F2 => egui::Key::F2,
            KeyCode::F3 => egui::Key::F3,
            KeyCode::F4 => egui::Key::F4,
            KeyCode::F5 => egui::Key::F5,
            KeyCode::F6 => egui::Key::F6,
            KeyCode::F7 => egui::Key::F7,
            KeyCode::F8 => egui::Key::F8,
            KeyCode::F9 => egui::Key::F9,
            KeyCode::F10 => egui::Key::F10,
            KeyCode::F11 => egui::Key::F11,
            KeyCode::F12 => egui::Key::F12,
            KeyCode::Escape => egui::Key::Escape,
            KeyCode::Tab => egui::Key::Tab,
            KeyCode::Space => egui::Key::Space,
            KeyCode::Enter => egui::Key::Enter,
            KeyCode::Backspace => egui::Key::Backspace,
            KeyCode::Delete => egui::Key::Delete,
            KeyCode::ArrowUp => egui::Key::ArrowUp,
            KeyCode::ArrowDown => egui::Key::ArrowDown,
            KeyCode::ArrowLeft => egui::Key::ArrowLeft,
            KeyCode::ArrowRight => egui::Key::ArrowRight,
            KeyCode::Home => egui::Key::Home,
            KeyCode::End => egui::Key::End,
            KeyCode::PageUp => egui::Key::PageUp,
            KeyCode::PageDown => egui::Key::PageDown,
        }
    }
}
