# xtreme.pyi - Type stubs for IDE autocompletion
from typing import Dict, List, Any, Optional

def get_position(ctx: Dict[str, Any], object_id: Optional[int] = None) -> List[float]: ...
def set_position(ctx: Dict[str, Any], x: float, y: float, z: float) -> None: ...
def translate(ctx: Dict[str, Any], dx: float, dy: float, dz: float) -> None: ...
def get_rotation(ctx: Dict[str, Any]) -> List[float]: ...
def set_rotation(ctx: Dict[str, Any], x: float, y: float, z: float) -> None: ...
def rotate(ctx: Dict[str, Any], rx: float, ry: float, rz: float) -> None: ...
def get_scale(ctx: Dict[str, Any]) -> List[float]: ...
def set_scale(ctx: Dict[str, Any], x: float, y: float, z: float) -> None: ...
def get_time(ctx: Dict[str, Any]) -> float: ...
def is_key_pressed(ctx: Dict[str, Any], key: str) -> bool: ...
def is_key_just_pressed(ctx: Dict[str, Any], key: str) -> bool: ...
def log_info(message: str) -> None: ...
def log_warn(message: str) -> None: ...
def log_error(message: str) -> None: ...
